name: 23f3001082@ds.study.iitm.ac.in

on:
  schedule:
    - cron: "30 2 * * *"  # Runs daily at 02:30 UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Make changes to a file
        run: |
          echo "Last updated: $(date -u)" > last_run.txt

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "23f3001082@ds.study.iitm.ac.in"
          git add last_run.txt
          git commit -m "Automated update: $(date -u)" || echo "No changes to commit"
          git push origin main